name = "RetroSignalModel"
uuid = "413adb04-e75d-4cfe-b7ca-413dd9cc07d4"
authors = ["stevengogogo <stevengogogo4321@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
